added person information and feedback form
AndChuiko/Castaway pull request #2
Opened 2024-04-01 18:18 UTC by AndChuiko

2024-04-02 17:59 UTC, aleksejchuikoo requested changes
В целом работа хорошая, но есть замечания небольшие, которые можно быстро исправить.

Единственное с чем тебе придется немного помучаться, так как это с формой, наверное.

2024-04-02 17:59 UTC, aleksejchuikoo commented on assets/images/arrow.png
Есть различные расширения для изображений/иконок: jpeg, png, svg. Нужно уметь тоже правильно их использовать. Сейчас проведу краткий экскурс по этим расширениям:

- JPEG (Joint Photographic Experts Group):
Лучше использовать для фотографий или изображений с непрерывными тональными переходами.
Поддерживает сжатие с потерями, что может снизить качество изображения, но сокращает размер файла.

- PNG (Portable Network Graphics):
Подходит для изображений с прозрачностью и/или высоким качеством, таких как логотипы, иллюстрации, и изображения с текстом.
Поддерживает альфа-канал, что позволяет создавать изображения с прозрачными областями.
Не поддерживает сжатие с потерями, что означает более высокое качество изображения, но может привести к большему размеру файла по сравнению с JPEG.

- SVG (Scalable Vector Graphics):
Используется для векторной графики, которая масштабируется без потери качества.
Подходит для иконок, диаграмм, и других графических элементов, которые могут быть масштабированы до любого размера без искажений.

В твоем случае, ты используешь для иконок png, что является плохой практикой, так как файлы эти будут  много занимать памяти. Простенькие иконки, такие как эта, можно и самому верстать, тогда в дальнейшем ты сможешь и анимации им запросто придавать + сайт не будет тратить ещё дополнительные ресурсы для подгрузки этой статики.
Если сам иконку не хочешь верстать, то можешь тогда использовать svg. Ты когда из figma экспортируешь, то у тебя предлагаются различные форматы экспорта.

Если используешь jpeg или png, то по-хорошему тогда перед этим где-нибудь в онлайне сжать твою фотографию.

2024-04-02 17:59 UTC, aleksejchuikoo commented on assets/images/person.png
Эта фотография не нуждается в png, достаточно будет jpeg, как и объяснял уже для иконки со стрелкой.

2024-04-02 17:59 UTC, aleksejchuikoo commented on index.html
> +                    <img class="person__img-arrow mrg" src="./assets/images/arrow.png" alt="">
Не забывай для изображений прописывать альтернативный текст на тот случай, если изображение не подгрузилось или какой-то человек с ограниченными возможностями будет с помощью screen readers изучать твой сайт.

P.S. В остальных случаях тоже поправь.

2024-04-02 17:59 UTC, aleksejchuikoo commented on index.html
> +                <a class="person__btn" href="#">
Если при нажатии на изображение не должно быть перехода по ссылке, а должно выполняться какое-то действие (например, открытие модального окна или отправка формы), тогда лучше использовать кнопку `<button>`. Тут уже задумку твою не знаю, поэтому отталкивайся от моих слов и поправь, если что.

2024-04-02 17:59 UTC, aleksejchuikoo commented on index.html
> +                <h4 class="person__text-h4 mrg">Meet your host</h4>
Что такое `mrg`? Данный нейминг не даёт четкого определения того, что выполняет твой класс.
Это чем-то смахивает на методологию Atomic CSS. Почитай про неё и исправь, к примеру, на `mb-20`

2024-04-02 17:59 UTC, aleksejchuikoo commented on index.html
> +                <form action="/">
Посмотри как правильно верстаются формы, а то у тебя каждый `input` и `label` обернут в `form`, что неправильно, так как кнопка отправик "Submit" должна отправлять все данные из этих полей.

`form` должен один оборачивать все эти `input` и `label` в твоём случае.

2024-04-02 17:59 UTC, aleksejchuikoo commented on index.html
> +                    <a class="feedback__btn" href="#">Submit</a>
Использовать тег `a` в данном случае будет семантически неправильно. Это должна быть кнопка с `type="submit"`, а также она должна находиться внутри твоей `form`.

2024-04-02 17:59 UTC, aleksejchuikoo commented on style.css
> +.person .person__img-arrow {
Может и не стоит тогда добавлять класс `person__img-arrow`, если он нигда не используется и не планируется?
Касается и других классов, которые ты здесь объявил, но стилей у них никаких нет

2024-04-02 17:59 UTC, aleksejchuikoo commented on style.css
>  color: #FFFFFFB2;
Не забывай цвета в переменные добавлять, а то я вижу, что у тебя дублирование происходит этого цвета и вот этого `#118DA8`

2024-04-02 17:59 UTC, aleksejchuikoo commented on style.css
> +letter-spacing: 2.880000114440918px;
Необязательно писать такую огромную точность. Лучше уже до сотых округлять.

2024-04-02 17:59 UTC, aleksejchuikoo commented on style.css
> +.person .person__text-h2 {
Ставь отступ в одну пустую строку между классами, чтобы не сливалось и было проще читать. Ну и отступы слева чтобы одинаковые были.
В дальнейшем мы будем использовать инструменты, которые сами автоматически будут править код и добавлять отступы и так далее, но пока набивай руку, чтобы сходу самому уметь красиво писать.

2024-04-02 17:59 UTC, aleksejchuikoo commented on style.css
> +    color: #118DA8;
У этого класса, как и у `.person__text-h4` одинаковые стили. Может стоило бы тогда вынести это в какой-то отдельный класс эти общие стили?

2024-04-02 17:59 UTC, aleksejchuikoo commented on style.css
> +margin-bottom: 0px;
У тебя тут четыре margin используется. Замени на один margin: 160px 70px 0 70px;

2024-04-04 17:39 UTC, aleksejchuikoo requested changes

2024-04-04 17:39 UTC, aleksejchuikoo commented on assets/images/arrow.svg
<img width="186" alt="Screenshot 2024-04-04 at 20 15 03" src="https://github.com/AndChuiko/Castaway/assets/43813650/533136eb-ffe1-49e8-9670-c7ca417c3fbd">
Брат, стрелочка точна такая должна быть?))
Что-то ей плохо, либо тут как-то не так отображается

2024-04-04 17:39 UTC, aleksejchuikoo commented on assets/images/arrow.jpg
Почему одна стрелка в jpg, а вторая в svg? Сделай две в svg

2024-04-04 17:39 UTC, aleksejchuikoo commented on index.html
> +                       <a href="#"><img class="main__icons" src="./assets/images/icons_5.svg" alt=""></a>
Название иконкам нормальные давай, в зависимости от их роли. К примеру spotify_icon.svg

Если другой человек захочет переиспользовать эту же иконку в другом месте, в котором ему нужно, то ему будет тяжело найти её, так как нет корректного названия. А если не найдёт, то добавит потом такую же иконку с другим названием, а это уже плохо, так как дублирование идёт.

Есть такой принцип разработки DRY (Don't repeat yourself), почитай про него, так как ты его будешь постоянно придерживаться во время разработки + на собесах могут спрашивать. 
Спустя время перейдём ещё к другим принципам (KISS, YAGNI, BDUF, APO). Если хочешь, то можешь тоже про них почитать, но это не к спеху

2024-04-04 17:39 UTC, aleksejchuikoo commented on style.css
> +.episodes .mb-30{
Ты можешь просто `.mb-30` вынести, как отдельные стили с таким классом, так как этот класс ты возможно будешь переиспользовать во всём приложении. А в твоём случае получается так, что оно только будет работать для элементов, которые внутри `.episodes` и` .person`. Когда вынесешь, то избавишься также от дублирования, то есть уберешь написанные тобой селекторы `.episodes .mb-30{` и `.person .mb-30{`, а останется только 
```
.mb-30 {
    margin-bottom: 30px;
}
```

2024-04-04 17:39 UTC, aleksejchuikoo commented on style.css
> +letter-spacing: 2.9px;
Я писал про сотые, но можно, конечно, и до десятых округлять)

2024-04-04 17:39 UTC, aleksejchuikoo commented on style.css
> +COLOR: var(--color-gray);
Почему COLOR капсом?

2024-04-04 17:39 UTC, aleksejchuikoo commented on style.css
> +} */
Это тебе ещё понадобится? Если нет, то не забывай комментарии удалять

2024-04-04 17:39 UTC, aleksejchuikoo commented on style.css
> +    align-content: center;
Разве `align-content: center;` будет работать с `display: block;`? Он же с флексами только заработает

2024-04-04 17:39 UTC, aleksejchuikoo commented on style.css
>      background: #191919;
Выноси тоже в переменную `#191919`. В 5 местах используется у тебя

2024-04-04 19:22 UTC, AndChuiko commented on assets/images/arrow.svg
Удалено

2024-04-04 19:22 UTC, AndChuiko commented on assets/images/arrow.jpg
Оставил в png

2024-04-04 19:42 UTC, AndChuiko commented on index.html
> +                       <a href="#"><img class="main__icons" src="./assets/images/icons_5.svg" alt=""></a>
Заставил меня найти их все

2024-04-04 19:45 UTC, AndChuiko commented on style.css
> +COLOR: var(--color-gray);
иногда среди нас находятся выделяющиеся личности , которые ломают шаблоны и вынуждают всех развиваться

2024-04-04 19:52 UTC, AndChuiko commented on style.css
> +    align-content: center;
Вроде как не должно, но работает. Вероятно потому что у родителя flex

2024-04-07 17:59 UTC, aleksejchuikoo commented on style.css
> +COLOR: var(--color-gray);
так красиво и завуалированно написал про меня :)
приятно...

2024-04-07 18:10 UTC, aleksejchuikoo approved these changes

2024-04-07 19:46 UTC, merged